name: Node.js CI

on:
  push:
    branches: ["Workflows"]
  pull_request:
    branches: ["Workflows"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: declaration-online/client/package-lock.json

      - name: Check client directory contents
        run: ls
        working-directory: declaration-online/client

      - name: Install dependencies
        run: npm ci
        working-directory: declaration-online/client

      - name: Build the client
        run: npm run build
        working-directory: declaration-online/client
